// +build !ignore_autogenerated

/*
Copyright 2021.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComputeGroupServiceStatus) DeepCopyInto(out *ComputeGroupServiceStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComputeGroupServiceStatus.
func (in *ComputeGroupServiceStatus) DeepCopy() *ComputeGroupServiceStatus {
	if in == nil {
		return nil
	}
	out := new(ComputeGroupServiceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatafuseComputeGroup) DeepCopyInto(out *DatafuseComputeGroup) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatafuseComputeGroup.
func (in *DatafuseComputeGroup) DeepCopy() *DatafuseComputeGroup {
	if in == nil {
		return nil
	}
	out := new(DatafuseComputeGroup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DatafuseComputeGroup) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatafuseComputeGroupList) DeepCopyInto(out *DatafuseComputeGroupList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DatafuseComputeGroup, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatafuseComputeGroupList.
func (in *DatafuseComputeGroupList) DeepCopy() *DatafuseComputeGroupList {
	if in == nil {
		return nil
	}
	out := new(DatafuseComputeGroupList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DatafuseComputeGroupList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatafuseComputeGroupSpec) DeepCopyInto(out *DatafuseComputeGroupSpec) {
	*out = *in
	if in.ComputeLeaders != nil {
		in, out := &in.ComputeLeaders, &out.ComputeLeaders
		*out = new(DatafuseComputeSetSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.ComputeWorkers != nil {
		in, out := &in.ComputeWorkers, &out.ComputeWorkers
		*out = make([]*DatafuseComputeSetSpec, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(DatafuseComputeSetSpec)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatafuseComputeGroupSpec.
func (in *DatafuseComputeGroupSpec) DeepCopy() *DatafuseComputeGroupSpec {
	if in == nil {
		return nil
	}
	out := new(DatafuseComputeGroupSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatafuseComputeGroupStatus) DeepCopyInto(out *DatafuseComputeGroupStatus) {
	*out = *in
	if in.ReadyComputeLeaders != nil {
		in, out := &in.ReadyComputeLeaders, &out.ReadyComputeLeaders
		*out = make(map[string]ComputeInstanceState, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.ReadyComputeWorkers != nil {
		in, out := &in.ReadyComputeWorkers, &out.ReadyComputeWorkers
		*out = make(map[string]ComputeInstanceState, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	out.GroupServiceStatus = in.GroupServiceStatus
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatafuseComputeGroupStatus.
func (in *DatafuseComputeGroupStatus) DeepCopy() *DatafuseComputeGroupStatus {
	if in == nil {
		return nil
	}
	out := new(DatafuseComputeGroupStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatafuseComputeInstanceSpec) DeepCopyInto(out *DatafuseComputeInstanceSpec) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Cores != nil {
		in, out := &in.Cores, &out.Cores
		*out = new(int32)
		**out = **in
	}
	if in.CoreLimit != nil {
		in, out := &in.CoreLimit, &out.CoreLimit
		*out = new(string)
		**out = **in
	}
	if in.Memory != nil {
		in, out := &in.Memory, &out.Memory
		*out = new(string)
		**out = **in
	}
	if in.MemoryLimit != nil {
		in, out := &in.MemoryLimit, &out.MemoryLimit
		*out = new(string)
		**out = **in
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Image != nil {
		in, out := &in.Image, &out.Image
		*out = new(string)
		**out = **in
	}
	if in.ImagePullPolicy != nil {
		in, out := &in.ImagePullPolicy, &out.ImagePullPolicy
		*out = new(string)
		**out = **in
	}
	if in.Priority != nil {
		in, out := &in.Priority, &out.Priority
		*out = new(int32)
		**out = **in
	}
	if in.MysqlPort != nil {
		in, out := &in.MysqlPort, &out.MysqlPort
		*out = new(int32)
		**out = **in
	}
	if in.ClickhousePort != nil {
		in, out := &in.ClickhousePort, &out.ClickhousePort
		*out = new(int32)
		**out = **in
	}
	if in.HTTPPort != nil {
		in, out := &in.HTTPPort, &out.HTTPPort
		*out = new(int32)
		**out = **in
	}
	if in.RPCPort != nil {
		in, out := &in.RPCPort, &out.RPCPort
		*out = new(int32)
		**out = **in
	}
	if in.MetricsPort != nil {
		in, out := &in.MetricsPort, &out.MetricsPort
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatafuseComputeInstanceSpec.
func (in *DatafuseComputeInstanceSpec) DeepCopy() *DatafuseComputeInstanceSpec {
	if in == nil {
		return nil
	}
	out := new(DatafuseComputeInstanceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatafuseComputeInstanceStatus) DeepCopyInto(out *DatafuseComputeInstanceStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatafuseComputeInstanceStatus.
func (in *DatafuseComputeInstanceStatus) DeepCopy() *DatafuseComputeInstanceStatus {
	if in == nil {
		return nil
	}
	out := new(DatafuseComputeInstanceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatafuseComputeSetSpec) DeepCopyInto(out *DatafuseComputeSetSpec) {
	*out = *in
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	in.DatafuseComputeInstanceSpec.DeepCopyInto(&out.DatafuseComputeInstanceSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatafuseComputeSetSpec.
func (in *DatafuseComputeSetSpec) DeepCopy() *DatafuseComputeSetSpec {
	if in == nil {
		return nil
	}
	out := new(DatafuseComputeSetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatafuseComputeSetStatus) DeepCopyInto(out *DatafuseComputeSetStatus) {
	*out = *in
	if in.InstancesStatus != nil {
		in, out := &in.InstancesStatus, &out.InstancesStatus
		*out = make(map[string]ComputeInstanceState, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatafuseComputeSetStatus.
func (in *DatafuseComputeSetStatus) DeepCopy() *DatafuseComputeSetStatus {
	if in == nil {
		return nil
	}
	out := new(DatafuseComputeSetStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatafuseOperator) DeepCopyInto(out *DatafuseOperator) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatafuseOperator.
func (in *DatafuseOperator) DeepCopy() *DatafuseOperator {
	if in == nil {
		return nil
	}
	out := new(DatafuseOperator)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DatafuseOperator) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatafuseOperatorList) DeepCopyInto(out *DatafuseOperatorList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DatafuseOperator, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatafuseOperatorList.
func (in *DatafuseOperatorList) DeepCopy() *DatafuseOperatorList {
	if in == nil {
		return nil
	}
	out := new(DatafuseOperatorList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DatafuseOperatorList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatafuseOperatorSpec) DeepCopyInto(out *DatafuseOperatorSpec) {
	*out = *in
	if in.ComputeGroups != nil {
		in, out := &in.ComputeGroups, &out.ComputeGroups
		*out = make([]*DatafuseComputeGroupSpec, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(DatafuseComputeGroupSpec)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.Version != nil {
		in, out := &in.Version, &out.Version
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatafuseOperatorSpec.
func (in *DatafuseOperatorSpec) DeepCopy() *DatafuseOperatorSpec {
	if in == nil {
		return nil
	}
	out := new(DatafuseOperatorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatafuseOperatorStatus) DeepCopyInto(out *DatafuseOperatorStatus) {
	*out = *in
	if in.ComputeGroupStates != nil {
		in, out := &in.ComputeGroupStates, &out.ComputeGroupStates
		*out = make(map[string]ComputeGroupState, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatafuseOperatorStatus.
func (in *DatafuseOperatorStatus) DeepCopy() *DatafuseOperatorStatus {
	if in == nil {
		return nil
	}
	out := new(DatafuseOperatorStatus)
	in.DeepCopyInto(out)
	return out
}
