// +build !ignore_autogenerated

/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	corev1 "k8s.io/api/core/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatafuseCluster) DeepCopyInto(out *DatafuseCluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatafuseCluster.
func (in *DatafuseCluster) DeepCopy() *DatafuseCluster {
	if in == nil {
		return nil
	}
	out := new(DatafuseCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DatafuseCluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatafuseClusterList) DeepCopyInto(out *DatafuseClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DatafuseCluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatafuseClusterList.
func (in *DatafuseClusterList) DeepCopy() *DatafuseClusterList {
	if in == nil {
		return nil
	}
	out := new(DatafuseClusterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DatafuseClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatafuseClusterSpec) DeepCopyInto(out *DatafuseClusterSpec) {
	*out = *in
	if in.ComputeGroups != nil {
		in, out := &in.ComputeGroups, &out.ComputeGroups
		*out = make([]*DatafuseComputeGroup, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(DatafuseComputeGroup)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatafuseClusterSpec.
func (in *DatafuseClusterSpec) DeepCopy() *DatafuseClusterSpec {
	if in == nil {
		return nil
	}
	out := new(DatafuseClusterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatafuseClusterStatus) DeepCopyInto(out *DatafuseClusterStatus) {
	*out = *in
	if in.ActiveComputeGroups != nil {
		in, out := &in.ActiveComputeGroups, &out.ActiveComputeGroups
		*out = make([]*DatafuseComputeGroup, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(DatafuseComputeGroup)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatafuseClusterStatus.
func (in *DatafuseClusterStatus) DeepCopy() *DatafuseClusterStatus {
	if in == nil {
		return nil
	}
	out := new(DatafuseClusterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatafuseComputeGroup) DeepCopyInto(out *DatafuseComputeGroup) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatafuseComputeGroup.
func (in *DatafuseComputeGroup) DeepCopy() *DatafuseComputeGroup {
	if in == nil {
		return nil
	}
	out := new(DatafuseComputeGroup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DatafuseComputeGroup) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatafuseComputeGroupList) DeepCopyInto(out *DatafuseComputeGroupList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DatafuseComputeGroup, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatafuseComputeGroupList.
func (in *DatafuseComputeGroupList) DeepCopy() *DatafuseComputeGroupList {
	if in == nil {
		return nil
	}
	out := new(DatafuseComputeGroupList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DatafuseComputeGroupList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatafuseComputeGroupSpec) DeepCopyInto(out *DatafuseComputeGroupSpec) {
	*out = *in
	if in.ComputeLeaders != nil {
		in, out := &in.ComputeLeaders, &out.ComputeLeaders
		*out = make([]*DatafuseComputeInstance, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(DatafuseComputeInstance)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatafuseComputeGroupSpec.
func (in *DatafuseComputeGroupSpec) DeepCopy() *DatafuseComputeGroupSpec {
	if in == nil {
		return nil
	}
	out := new(DatafuseComputeGroupSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatafuseComputeGroupStatus) DeepCopyInto(out *DatafuseComputeGroupStatus) {
	*out = *in
	if in.ReadyComputeLeaders != nil {
		in, out := &in.ReadyComputeLeaders, &out.ReadyComputeLeaders
		*out = make([]*DatafuseComputeInstance, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(DatafuseComputeInstance)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatafuseComputeGroupStatus.
func (in *DatafuseComputeGroupStatus) DeepCopy() *DatafuseComputeGroupStatus {
	if in == nil {
		return nil
	}
	out := new(DatafuseComputeGroupStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatafuseComputeInstance) DeepCopyInto(out *DatafuseComputeInstance) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatafuseComputeInstance.
func (in *DatafuseComputeInstance) DeepCopy() *DatafuseComputeInstance {
	if in == nil {
		return nil
	}
	out := new(DatafuseComputeInstance)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DatafuseComputeInstance) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatafuseComputeInstanceList) DeepCopyInto(out *DatafuseComputeInstanceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DatafuseComputeInstance, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatafuseComputeInstanceList.
func (in *DatafuseComputeInstanceList) DeepCopy() *DatafuseComputeInstanceList {
	if in == nil {
		return nil
	}
	out := new(DatafuseComputeInstanceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DatafuseComputeInstanceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatafuseComputeInstanceSpec) DeepCopyInto(out *DatafuseComputeInstanceSpec) {
	*out = *in
	if in.Cores != nil {
		in, out := &in.Cores, &out.Cores
		*out = new(int32)
		**out = **in
	}
	if in.EnvFrom != nil {
		in, out := &in.EnvFrom, &out.EnvFrom
		*out = make([]corev1.EnvFromSource, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Image != nil {
		in, out := &in.Image, &out.Image
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatafuseComputeInstanceSpec.
func (in *DatafuseComputeInstanceSpec) DeepCopy() *DatafuseComputeInstanceSpec {
	if in == nil {
		return nil
	}
	out := new(DatafuseComputeInstanceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatafuseComputeInstanceStatus) DeepCopyInto(out *DatafuseComputeInstanceStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatafuseComputeInstanceStatus.
func (in *DatafuseComputeInstanceStatus) DeepCopy() *DatafuseComputeInstanceStatus {
	if in == nil {
		return nil
	}
	out := new(DatafuseComputeInstanceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatafuseComputeSet) DeepCopyInto(out *DatafuseComputeSet) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatafuseComputeSet.
func (in *DatafuseComputeSet) DeepCopy() *DatafuseComputeSet {
	if in == nil {
		return nil
	}
	out := new(DatafuseComputeSet)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DatafuseComputeSet) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatafuseComputeSetList) DeepCopyInto(out *DatafuseComputeSetList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DatafuseComputeSet, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatafuseComputeSetList.
func (in *DatafuseComputeSetList) DeepCopy() *DatafuseComputeSetList {
	if in == nil {
		return nil
	}
	out := new(DatafuseComputeSetList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DatafuseComputeSetList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatafuseComputeSetSpec) DeepCopyInto(out *DatafuseComputeSetSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatafuseComputeSetSpec.
func (in *DatafuseComputeSetSpec) DeepCopy() *DatafuseComputeSetSpec {
	if in == nil {
		return nil
	}
	out := new(DatafuseComputeSetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatafuseComputeSetStatus) DeepCopyInto(out *DatafuseComputeSetStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatafuseComputeSetStatus.
func (in *DatafuseComputeSetStatus) DeepCopy() *DatafuseComputeSetStatus {
	if in == nil {
		return nil
	}
	out := new(DatafuseComputeSetStatus)
	in.DeepCopyInto(out)
	return out
}
