apiVersion: datafuse.datafuselabs.io/v1alpha1
kind: DatafuseComputeGroup
metadata:
  name: datafusecomputegroup-default
spec:
  # Add fields here
  leaders:
    spec:
      cores: 1
  # workers:
  # - spec:
  #     cores: 1
  # - spec:
  #     cores: 2
