/*
Copyright 2021.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	datafusev1alpha1 "datafuselabs.io/datafuse-operator/pkg/apis/datafuse/v1alpha1"
	versioned "datafuselabs.io/datafuse-operator/pkg/client/clientset/versioned"
	internalinterfaces "datafuselabs.io/datafuse-operator/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "datafuselabs.io/datafuse-operator/pkg/client/listers/datafuse/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// DatafuseComputeGroupInformer provides access to a shared informer and lister for
// DatafuseComputeGroups.
type DatafuseComputeGroupInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.DatafuseComputeGroupLister
}

type datafuseComputeGroupInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewDatafuseComputeGroupInformer constructs a new informer for DatafuseComputeGroup type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewDatafuseComputeGroupInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredDatafuseComputeGroupInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredDatafuseComputeGroupInformer constructs a new informer for DatafuseComputeGroup type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredDatafuseComputeGroupInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.DatafuseV1alpha1().DatafuseComputeGroups(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.DatafuseV1alpha1().DatafuseComputeGroups(namespace).Watch(context.TODO(), options)
			},
		},
		&datafusev1alpha1.DatafuseComputeGroup{},
		resyncPeriod,
		indexers,
	)
}

func (f *datafuseComputeGroupInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredDatafuseComputeGroupInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *datafuseComputeGroupInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&datafusev1alpha1.DatafuseComputeGroup{}, f.defaultInformer)
}

func (f *datafuseComputeGroupInformer) Lister() v1alpha1.DatafuseComputeGroupLister {
	return v1alpha1.NewDatafuseComputeGroupLister(f.Informer().GetIndexer())
}
