# permissions for end users to edit datafuseoperators.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: datafuseoperator-editor-role
rules:
- apiGroups:
  - datafuse.datafuselabs.io
  resources:
  - datafuseoperators
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - datafuse.datafuselabs.io
  resources:
  - datafuseoperators/status
  verbs:
  - get
