# permissions for end users to edit datafusecomputeinstances.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: datafusecomputeinstance-editor-role
rules:
- apiGroups:
  - datafuse.datafuselabs.io
  resources:
  - datafusecomputeinstances
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - datafuse.datafuselabs.io
  resources:
  - datafusecomputeinstances/status
  verbs:
  - get
