# permissions for end users to view datafusecomputesets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: datafusecomputeset-viewer-role
rules:
- apiGroups:
  - datafuseoperator.datafuselabs.io
  resources:
  - datafusecomputesets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - datafuseoperator.datafuselabs.io
  resources:
  - datafusecomputesets/status
  verbs:
  - get
