# permissions for end users to edit datafusecomputegroups.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: datafusecomputegroup-editor-role
rules:
- apiGroups:
  - datafuseoperator.datafuselabs.io
  resources:
  - datafusecomputegroups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - datafuseoperator.datafuselabs.io
  resources:
  - datafusecomputegroups/status
  verbs:
  - get
