/*
Copyright 2021.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "datafuselabs.io/datafuse-operator/pkg/apis/datafuse/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeDatafuseOperators implements DatafuseOperatorInterface
type FakeDatafuseOperators struct {
	Fake *FakeDatafuseV1alpha1
	ns   string
}

var datafuseoperatorsResource = schema.GroupVersionResource{Group: "datafuse", Version: "v1alpha1", Resource: "datafuseoperators"}

var datafuseoperatorsKind = schema.GroupVersionKind{Group: "datafuse", Version: "v1alpha1", Kind: "DatafuseOperator"}

// Get takes name of the datafuseOperator, and returns the corresponding datafuseOperator object, and an error if there is any.
func (c *FakeDatafuseOperators) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.DatafuseOperator, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(datafuseoperatorsResource, c.ns, name), &v1alpha1.DatafuseOperator{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DatafuseOperator), err
}

// List takes label and field selectors, and returns the list of DatafuseOperators that match those selectors.
func (c *FakeDatafuseOperators) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.DatafuseOperatorList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(datafuseoperatorsResource, datafuseoperatorsKind, c.ns, opts), &v1alpha1.DatafuseOperatorList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.DatafuseOperatorList{ListMeta: obj.(*v1alpha1.DatafuseOperatorList).ListMeta}
	for _, item := range obj.(*v1alpha1.DatafuseOperatorList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested datafuseOperators.
func (c *FakeDatafuseOperators) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(datafuseoperatorsResource, c.ns, opts))

}

// Create takes the representation of a datafuseOperator and creates it.  Returns the server's representation of the datafuseOperator, and an error, if there is any.
func (c *FakeDatafuseOperators) Create(ctx context.Context, datafuseOperator *v1alpha1.DatafuseOperator, opts v1.CreateOptions) (result *v1alpha1.DatafuseOperator, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(datafuseoperatorsResource, c.ns, datafuseOperator), &v1alpha1.DatafuseOperator{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DatafuseOperator), err
}

// Update takes the representation of a datafuseOperator and updates it. Returns the server's representation of the datafuseOperator, and an error, if there is any.
func (c *FakeDatafuseOperators) Update(ctx context.Context, datafuseOperator *v1alpha1.DatafuseOperator, opts v1.UpdateOptions) (result *v1alpha1.DatafuseOperator, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(datafuseoperatorsResource, c.ns, datafuseOperator), &v1alpha1.DatafuseOperator{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DatafuseOperator), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeDatafuseOperators) UpdateStatus(ctx context.Context, datafuseOperator *v1alpha1.DatafuseOperator, opts v1.UpdateOptions) (*v1alpha1.DatafuseOperator, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(datafuseoperatorsResource, "status", c.ns, datafuseOperator), &v1alpha1.DatafuseOperator{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DatafuseOperator), err
}

// Delete takes name of the datafuseOperator and deletes it. Returns an error if one occurs.
func (c *FakeDatafuseOperators) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(datafuseoperatorsResource, c.ns, name), &v1alpha1.DatafuseOperator{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeDatafuseOperators) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(datafuseoperatorsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.DatafuseOperatorList{})
	return err
}

// Patch applies the patch and returns the patched datafuseOperator.
func (c *FakeDatafuseOperators) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.DatafuseOperator, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(datafuseoperatorsResource, c.ns, name, pt, data, subresources...), &v1alpha1.DatafuseOperator{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DatafuseOperator), err
}
