/*
Copyright 2021.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "datafuselabs.io/datafuse-operator/pkg/apis/datafuse/v1alpha1"
	scheme "datafuselabs.io/datafuse-operator/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// DatafuseComputeGroupsGetter has a method to return a DatafuseComputeGroupInterface.
// A group's client should implement this interface.
type DatafuseComputeGroupsGetter interface {
	DatafuseComputeGroups(namespace string) DatafuseComputeGroupInterface
}

// DatafuseComputeGroupInterface has methods to work with DatafuseComputeGroup resources.
type DatafuseComputeGroupInterface interface {
	Create(ctx context.Context, datafuseComputeGroup *v1alpha1.DatafuseComputeGroup, opts v1.CreateOptions) (*v1alpha1.DatafuseComputeGroup, error)
	Update(ctx context.Context, datafuseComputeGroup *v1alpha1.DatafuseComputeGroup, opts v1.UpdateOptions) (*v1alpha1.DatafuseComputeGroup, error)
	UpdateStatus(ctx context.Context, datafuseComputeGroup *v1alpha1.DatafuseComputeGroup, opts v1.UpdateOptions) (*v1alpha1.DatafuseComputeGroup, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.DatafuseComputeGroup, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.DatafuseComputeGroupList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.DatafuseComputeGroup, err error)
	DatafuseComputeGroupExpansion
}

// datafuseComputeGroups implements DatafuseComputeGroupInterface
type datafuseComputeGroups struct {
	client rest.Interface
	ns     string
}

// newDatafuseComputeGroups returns a DatafuseComputeGroups
func newDatafuseComputeGroups(c *DatafuseV1alpha1Client, namespace string) *datafuseComputeGroups {
	return &datafuseComputeGroups{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the datafuseComputeGroup, and returns the corresponding datafuseComputeGroup object, and an error if there is any.
func (c *datafuseComputeGroups) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.DatafuseComputeGroup, err error) {
	result = &v1alpha1.DatafuseComputeGroup{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("datafusecomputegroups").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of DatafuseComputeGroups that match those selectors.
func (c *datafuseComputeGroups) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.DatafuseComputeGroupList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.DatafuseComputeGroupList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("datafusecomputegroups").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested datafuseComputeGroups.
func (c *datafuseComputeGroups) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("datafusecomputegroups").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a datafuseComputeGroup and creates it.  Returns the server's representation of the datafuseComputeGroup, and an error, if there is any.
func (c *datafuseComputeGroups) Create(ctx context.Context, datafuseComputeGroup *v1alpha1.DatafuseComputeGroup, opts v1.CreateOptions) (result *v1alpha1.DatafuseComputeGroup, err error) {
	result = &v1alpha1.DatafuseComputeGroup{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("datafusecomputegroups").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(datafuseComputeGroup).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a datafuseComputeGroup and updates it. Returns the server's representation of the datafuseComputeGroup, and an error, if there is any.
func (c *datafuseComputeGroups) Update(ctx context.Context, datafuseComputeGroup *v1alpha1.DatafuseComputeGroup, opts v1.UpdateOptions) (result *v1alpha1.DatafuseComputeGroup, err error) {
	result = &v1alpha1.DatafuseComputeGroup{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("datafusecomputegroups").
		Name(datafuseComputeGroup.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(datafuseComputeGroup).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *datafuseComputeGroups) UpdateStatus(ctx context.Context, datafuseComputeGroup *v1alpha1.DatafuseComputeGroup, opts v1.UpdateOptions) (result *v1alpha1.DatafuseComputeGroup, err error) {
	result = &v1alpha1.DatafuseComputeGroup{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("datafusecomputegroups").
		Name(datafuseComputeGroup.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(datafuseComputeGroup).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the datafuseComputeGroup and deletes it. Returns an error if one occurs.
func (c *datafuseComputeGroups) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("datafusecomputegroups").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *datafuseComputeGroups) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("datafusecomputegroups").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched datafuseComputeGroup.
func (c *datafuseComputeGroups) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.DatafuseComputeGroup, err error) {
	result = &v1alpha1.DatafuseComputeGroup{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("datafusecomputegroups").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
