/*
Copyright 2021.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "datafuselabs.io/datafuse-operator/pkg/apis/datafuse/v1alpha1"
	scheme "datafuselabs.io/datafuse-operator/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// DatafuseOperatorsGetter has a method to return a DatafuseOperatorInterface.
// A group's client should implement this interface.
type DatafuseOperatorsGetter interface {
	DatafuseOperators(namespace string) DatafuseOperatorInterface
}

// DatafuseOperatorInterface has methods to work with DatafuseOperator resources.
type DatafuseOperatorInterface interface {
	Create(ctx context.Context, datafuseOperator *v1alpha1.DatafuseOperator, opts v1.CreateOptions) (*v1alpha1.DatafuseOperator, error)
	Update(ctx context.Context, datafuseOperator *v1alpha1.DatafuseOperator, opts v1.UpdateOptions) (*v1alpha1.DatafuseOperator, error)
	UpdateStatus(ctx context.Context, datafuseOperator *v1alpha1.DatafuseOperator, opts v1.UpdateOptions) (*v1alpha1.DatafuseOperator, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.DatafuseOperator, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.DatafuseOperatorList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.DatafuseOperator, err error)
	DatafuseOperatorExpansion
}

// datafuseOperators implements DatafuseOperatorInterface
type datafuseOperators struct {
	client rest.Interface
	ns     string
}

// newDatafuseOperators returns a DatafuseOperators
func newDatafuseOperators(c *DatafuseV1alpha1Client, namespace string) *datafuseOperators {
	return &datafuseOperators{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the datafuseOperator, and returns the corresponding datafuseOperator object, and an error if there is any.
func (c *datafuseOperators) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.DatafuseOperator, err error) {
	result = &v1alpha1.DatafuseOperator{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("datafuseoperators").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of DatafuseOperators that match those selectors.
func (c *datafuseOperators) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.DatafuseOperatorList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.DatafuseOperatorList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("datafuseoperators").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested datafuseOperators.
func (c *datafuseOperators) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("datafuseoperators").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a datafuseOperator and creates it.  Returns the server's representation of the datafuseOperator, and an error, if there is any.
func (c *datafuseOperators) Create(ctx context.Context, datafuseOperator *v1alpha1.DatafuseOperator, opts v1.CreateOptions) (result *v1alpha1.DatafuseOperator, err error) {
	result = &v1alpha1.DatafuseOperator{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("datafuseoperators").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(datafuseOperator).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a datafuseOperator and updates it. Returns the server's representation of the datafuseOperator, and an error, if there is any.
func (c *datafuseOperators) Update(ctx context.Context, datafuseOperator *v1alpha1.DatafuseOperator, opts v1.UpdateOptions) (result *v1alpha1.DatafuseOperator, err error) {
	result = &v1alpha1.DatafuseOperator{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("datafuseoperators").
		Name(datafuseOperator.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(datafuseOperator).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *datafuseOperators) UpdateStatus(ctx context.Context, datafuseOperator *v1alpha1.DatafuseOperator, opts v1.UpdateOptions) (result *v1alpha1.DatafuseOperator, err error) {
	result = &v1alpha1.DatafuseOperator{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("datafuseoperators").
		Name(datafuseOperator.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(datafuseOperator).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the datafuseOperator and deletes it. Returns an error if one occurs.
func (c *datafuseOperators) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("datafuseoperators").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *datafuseOperators) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("datafuseoperators").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched datafuseOperator.
func (c *datafuseOperators) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.DatafuseOperator, err error) {
	result = &v1alpha1.DatafuseOperator{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("datafuseoperators").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
